version: "3"
services:
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.0.32
    command: -Dconfig.resource=dev-mode.conf
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8081}
      PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
      VIEW_FEATURES_ALL: on
